name: CI
on: [ push ]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Install Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test
